"""added manufacturer

Revision ID: b5c1e84d838e
Revises: ecd9c1807b1c
Create Date: 2025-06-29 18:09:23.854203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c1e84d838e'
down_revision: Union[str, Sequence[str], None] = 'ecd9c1807b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('manufacturer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'manufacturer')
    # ### end Alembic commands ###
